name: Build Markdown files
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:3.1
        with:
          entrypoint: /github/workflow/run.sh
      - name: Commit and push
        run: |
          ls -R
          git checkout pages
