name: Build HTML
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 28.2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        shell: 'script -q -e -c "bash {0}" /dev/null'
        run: make
      - name: Commit and push
        run: |
          git checkout pages
          cp -r dist/* docs
          rm -r dist
          git status
          git config user.name yhiraki
          git config user.email yhiraki@users.noreply.github.com
          git add docs
          git commit -m 'update'
          git push origin pages
