name: Build Markdown files
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:3.1
        with:
          entrypoint: /github/workspace/run.sh
      - uses: actions/checkout@v3
        with:
          ref: pages
      - name: Commit and push
        run: |
          git add **/*.md
          git status
